# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./dockerfile.serving
#      args:
#        ARG: <ARG>
    image: ift6758/serving:model-serving
    ports:
      - 8080:8080
    environment:
#      DOCKER_ENV_VAR = ${LOCAL_ENV_VAR}
      - COMET_API_KEY=${COMET_API_KEY}
###### Uncomment below when you're ready to add the final notebook container to your docker compose
  streamlit:
    build:
      context: ./
      dockerfile: ./dockerfile.streamlit
##      args:
##        ARG: <ARG>
    image: ift6758/streamlit:model-serving_1
    ports:
      - 8850:8850
    environment:
      #OTHER_DOCKER_ENV_VAR = ${OTHER_LOCAL_ENV_VAR}
      - COMET_API_KEY=${COMET_API_KEY} 
      

     
